// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyS7bw02TWUVPmtINeQ47LCEBtrsfhUmc',
    appId: '1:129854182358:web:6462a0f4181351691e8a77',
    messagingSenderId: '129854182358',
    projectId: 'kalikomonitoringlistrik',
    authDomain: 'kalikomonitoringlistrik.firebaseapp.com',
    databaseURL: 'https://kalikomonitoringlistrik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalikomonitoringlistrik.firebasestorage.app',
    measurementId: 'G-WVPKPZRGZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAixiuvZ9Jqlp2TPBWgmfXKuTwIIxmttO0',
    appId: '1:129854182358:android:aa38c45a5a5efbc31e8a77',
    messagingSenderId: '129854182358',
    projectId: 'kalikomonitoringlistrik',
    databaseURL: 'https://kalikomonitoringlistrik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalikomonitoringlistrik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyHDn3cyvlimVuP8CYWvjMNOkaCuIW6f4',
    appId: '1:129854182358:ios:a592f8ddc73bcf8b1e8a77',
    messagingSenderId: '129854182358',
    projectId: 'kalikomonitoringlistrik',
    databaseURL: 'https://kalikomonitoringlistrik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalikomonitoringlistrik.firebasestorage.app',
    iosBundleId: 'com.example.kaliko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyHDn3cyvlimVuP8CYWvjMNOkaCuIW6f4',
    appId: '1:129854182358:ios:a592f8ddc73bcf8b1e8a77',
    messagingSenderId: '129854182358',
    projectId: 'kalikomonitoringlistrik',
    databaseURL: 'https://kalikomonitoringlistrik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalikomonitoringlistrik.firebasestorage.app',
    iosBundleId: 'com.example.kaliko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyS7bw02TWUVPmtINeQ47LCEBtrsfhUmc',
    appId: '1:129854182358:web:d97086929059b8801e8a77',
    messagingSenderId: '129854182358',
    projectId: 'kalikomonitoringlistrik',
    authDomain: 'kalikomonitoringlistrik.firebaseapp.com',
    databaseURL: 'https://kalikomonitoringlistrik-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kalikomonitoringlistrik.firebasestorage.app',
    measurementId: 'G-7CPG6BK691',
  );
}
